export const articlePageCopy = {
  fr: {
    title: "Articles de géologie, d’eau et d’environnement",
    heading: "Lire le territoire, couche par couche.",
    kicker: "Carnet de terrain · GEOANALYSIS",
    lead: "Six repères documentés pour comprendre les roches, l’eau et les paysages qui les relient.",
    description: "Guides de GEOANALYSIS sur la télédétection, la cartographie géologique, les eaux souterraines et l’environnement.",
    collection: "Le dossier",
    count: "fiches pour lire le terrain",
    indexKicker: "Géologie · Eau · Environnement",
    indexTitle: "Des méthodes, des repères, du contexte.",
    indexLead: "Parcourez les fiches, puis consultez les références liées à chaque sujet.",
    featured: "À lire d’abord",
    read: "de lecture",
    back: "Tous les articles",
    related: "Autres articles",
    contact: "Parler de votre projet",
    sources: "Sources et références",
  },
  en: {
    title: "Geology, water and environment articles",
    heading: "Read the landscape, layer by layer.",
    kicker: "Field notes · GEOANALYSIS",
    lead: "Six sourced guides to the rocks, water and landscapes that connect them.",
    description: "GEOANALYSIS guides to remote sensing, geological mapping, groundwater and environmental assessment.",
    collection: "The collection",
    count: "field guides to explore",
    indexKicker: "Geology · Water · Environment",
    indexTitle: "Methods, landmarks and context.",
    indexLead: "Browse each guide, then follow its linked references for more detail.",
    featured: "Start here",
    read: "read",
    back: "All articles",
    related: "More articles",
    contact: "Discuss your project",
    sources: "Sources and references",
  },
} as const;
