export const newsPageCopy = {
  fr: {
    title: "Actualités",
    lead: "Images d’archives et activités géologiques documentées dans les supports GEOANALYSIS.",
    description: "Archives de terrain de GEOANALYSIS : observations géologiques, affleurements et échantillonnage documentés.",
    archiveRange: "29 août 2023 — 22 août 2024",
    indexEyebrow: "Regards de terrain",
    indexTitle: "Le carnet du bureau",
    openStory: "Lire cette archive",
    back: "Toutes les actualités",
    related: "Autres actualités",
    read: "de lecture",
    archiveLabel: "Archives photographiques",
    sourceLabel: "Précision sur les sources",
    sourceNote: "Les documents fournis ne permettent pas d’associer ces archives à un site ou à un client précis.",
  },
  en: {
    title: "News",
    lead: "Archive images and geological activities documented in GEOANALYSIS materials.",
    description: "GEOANALYSIS field archives: documented geological observations, outcrops, and sampling.",
    archiveRange: "August 29, 2023 — August 22, 2024",
    indexEyebrow: "Field notes",
    indexTitle: "From the firm’s archive",
    openStory: "Read this archive",
    back: "All news",
    related: "More news",
    read: "read",
    archiveLabel: "Photo archive",
    sourceLabel: "Source note",
    sourceNote: "The supplied documents do not link these archive images to a specific site or client.",
  },
} as const;
