export const methodsPageCopy = {
  fr: {
    kicker: "Méthodes & technologies",
    title: "Du terrain à l’analyse.",
    lead: "Des observations géologiques aux cartes thématiques, chaque intervention s’appuie sur une méthode adaptée à la question étudiée et aux livrables attendus.",
    description: "Méthodes de terrain, études spécialisées, SIG et cartographie mobilisés par GEOANALYSIS selon les besoins du projet.",
    exploreAction: "Découvrir notre démarche",
    contactAction: "Échanger sur un projet",
    photoAlt: "Strates géologiques visibles dans un affleurement rocheux.",
    photoCaption: "Observer les formations sur le terrain",
    photoStamp: "Observation géologique",
    processKicker: "Une démarche adaptée",
    processTitle: "Du recueil terrain à la restitution",
    processLead: "Les étapes sont choisies selon le contexte de l’étude, les données disponibles et les résultats attendus.",
    technologyKicker: "Données géographiques",
    technologyTitle: "La carte rend les données lisibles.",
    technologyLead: "Les outils SIG, la cartographie et la télédétection structurent l’information spatiale pour faciliter la lecture d’un site et la transmission des résultats.",
    technologyNote: "Les outils mobilisés sont définis en fonction du périmètre et des données du projet.",
    mapCaption: "Schéma illustratif · lecture cartographique",
    mapVisualTitle: "SIG / CARTOGRAPHIE",
    mapVisualStart: "OBSERVATIONS",
    mapVisualEnd: "CARTES THÉMATIQUES",
    stages: [
      {
        id: "terrain",
        number: "01",
        label: "Terrain",
        title: "Observer et recueillir",
        description: "Documenter le site et réunir les informations utiles à l’étude.",
        items: ["Cartographie et levés géologiques", "Reconnaissance et échantillonnage", "Planification et suivi de sondages", "Prélèvements et analyses de l’eau in situ"],
      },
      {
        id: "etudes",
        number: "02",
        label: "Études",
        title: "Analyser le contexte",
        description: "Croiser les observations et approfondir les enjeux du projet.",
        items: ["Études hydrologiques et hydrogéologiques", "Études hydro-géophysiques", "Simulation hydraulique des zones inondables", "Évaluation environnementale"],
      },
      {
        id: "restitution",
        number: "03",
        label: "Restitution",
        title: "Structurer les résultats",
        description: "Présenter une information claire, exploitable et adaptée au projet.",
        items: ["Cartes thématiques", "Rapports bibliographiques et synthèses", "Formation en SIG et télédétection"],
      },
    ],
    outputs: ["Cartes minières, géophysiques et hydrologiques", "Lecture d’images et données par télédétection", "Rapports et synthèses cartographiques", "Formation aux méthodes SIG"],
  },
  en: {
    kicker: "Methods & technologies",
    title: "From fieldwork to analysis.",
    lead: "From geological observations to thematic maps, each assignment uses methods suited to the question being studied and the expected deliverables.",
    description: "Field methods, specialist studies, GIS and mapping used by GEOANALYSIS to meet project needs.",
    exploreAction: "Explore our approach",
    contactAction: "Discuss a project",
    photoAlt: "Geological strata exposed in a rocky outcrop.",
    photoCaption: "Observing formations in the field",
    photoStamp: "Geological observation",
    processKicker: "An adaptable approach",
    processTitle: "From field data to clear results",
    processLead: "Each step is selected to fit the study context, available data and expected results.",
    technologyKicker: "Geographic data",
    technologyTitle: "Maps make data easier to read.",
    technologyLead: "GIS, mapping and remote sensing organize spatial information to help interpret a site and communicate findings.",
    technologyNote: "The tools used are chosen to suit the project scope and available data.",
    mapCaption: "Illustrative diagram · map reading",
    mapVisualTitle: "GIS / MAPPING",
    mapVisualStart: "OBSERVATIONS",
    mapVisualEnd: "THEMATIC MAPS",
    stages: [
      {
        id: "terrain",
        number: "01",
        label: "Fieldwork",
        title: "Observe and collect",
        description: "Document the site and gather information relevant to the study.",
        items: ["Geological mapping and surveys", "Site reconnaissance and sampling", "Drill planning and supervision", "In-situ water sampling and analysis"],
      },
      {
        id: "etudes",
        number: "02",
        label: "Studies",
        title: "Analyze the context",
        description: "Combine observations and examine the project's key issues.",
        items: ["Hydrological and hydrogeological studies", "Hydrogeophysical studies", "Hydraulic simulation of flood zones", "Environmental assessment"],
      },
      {
        id: "restitution",
        number: "03",
        label: "Reporting",
        title: "Organize the findings",
        description: "Present clear, usable information suited to the project.",
        items: ["Thematic maps", "Literature reports and technical summaries", "GIS and remote-sensing training"],
      },
    ],
    outputs: ["Mining, geophysical and hydrological maps", "Image and data interpretation through remote sensing", "Reports and map-based summaries", "GIS methods training"],
  },
} as const;
