import type { Locale } from "@/lib/i18n";

export const expertisePageCopy = {
  fr: {
    indexTitle: "Nos expertises",
    indexLead: "Des études géologiques et minières aux missions d’hydrologie et d’environnement, découvrez les prestations GEOANALYSIS.",
    indexSectionKicker: "Domaines d’intervention",
    indexSectionTitle: "Trois champs d’intervention",
    openDetails: "Voir les prestations",
    detailKicker: "Nos expertises",
    backToIndex: "Toutes nos expertises",
    overview: "Domaines d’intervention",
    overviewTitle: "Géologie, mines, eau et environnement",
    servicesKicker: "Prestations",
    services: "Services proposés",
    relatedProjectsKicker: "Réalisations",
    relatedProjects: "Réalisations associées",
    projectImage: "MISSION GÉOSCIENTIFIQUE",
  },
  en: {
    indexTitle: "Our expertise",
    indexLead: "Explore GEOANALYSIS services, from geological and mining studies to hydrology and environmental work.",
    indexSectionKicker: "Areas of work",
    indexSectionTitle: "Three areas of work",
    openDetails: "View services",
    detailKicker: "Our expertise",
    backToIndex: "All expertise",
    overview: "Areas of work",
    overviewTitle: "Geology, mining, water and environment",
    servicesKicker: "Services",
    services: "Services offered",
    relatedProjectsKicker: "Projects",
    relatedProjects: "Related projects",
    projectImage: "GEOSCIENTIFIC ASSIGNMENT",
  },
} satisfies Record<Locale, Record<string, string>>;
