import type { Locale } from "@/lib/i18n";

export const expertisePageCopy = {
  fr: {
    indexTitle: "Nos expertises",
    indexLead: "Trois catégories principales, chacune déclinée en sous-services. Chaque domaine peut être mobilisé seul ou dans une mission intégrée, du cadrage initial au rapport final.",
    indexSectionKicker: "Domaines d’intervention",
    indexSectionTitle: "Trois domaines, un même socle méthodologique",
    openDetails: "Voir la page détaillée",
    detailKicker: "Nos expertises",
    backToIndex: "Toutes nos expertises",
    context: "Contexte",
    contextTitle: "Contexte & problématique",
    approach: "Notre approche",
    methodologyKicker: "Méthodologie",
    methodology: "Méthodologie étape par étape",
    technologies: "Technologies utilisées",
    deliverables: "Livrables",
    audience: "Public cible",
    relatedProjectsKicker: "Réalisations",
    relatedProjects: "Réalisations associées",
    projectImage: "MISSION GÉOSCIENTIFIQUE",
  },
  en: {
    indexTitle: "Our expertise",
    indexLead: "Three main fields, each split into sub-services. Each field can be commissioned on its own or as an integrated assignment, from initial scoping to final report.",
    indexSectionKicker: "Areas of work",
    indexSectionTitle: "Three fields, one methodological foundation",
    openDetails: "View detailed page",
    detailKicker: "Expertise",
    backToIndex: "All expertise",
    context: "Context",
    contextTitle: "Context & problem",
    approach: "Our approach",
    methodologyKicker: "Methodology",
    methodology: "Step-by-step methodology",
    technologies: "Technology used",
    deliverables: "Deliverables",
    audience: "Intended for",
    relatedProjectsKicker: "Projects",
    relatedProjects: "Related projects",
    projectImage: "GEOSCIENTIFIC ASSIGNMENT",
  },
} satisfies Record<Locale, Record<string, string>>;
