import type { Locale } from "@/lib/i18n";

export const contactPageCopy = {
  fr: {
    kicker: "Contact",
    title: "Parlons de votre projet",
    description: "Contactez GEOANALYSIS pour cadrer une mission en géologie, géophysique ou environnement.",
    name: "Nom",
    company: "Société",
    email: "Email",
    phone: "Téléphone",
    optional: "(facultatif)",
    projectType: "Type de projet",
    message: "Message",
    projectTypes: [
      { label: "Exploration minière", value: "mining" },
      { label: "Étude d’impact", value: "impact" },
      { label: "Ressources en eau", value: "water" },
      { label: "Autre", value: "other" },
    ],
    send: "Envoyer la demande",
    success: "Démo locale validée. Votre demande n’a été ni envoyée ni enregistrée.",
    demoNote: "Démo locale uniquement : votre demande n’est ni envoyée ni enregistrée.",
    errors: {
      name: "Indiquez votre nom.",
      emailRequired: "Indiquez votre adresse email.",
      emailInvalid: "Saisissez une adresse email valide, par exemple nom@entreprise.ma.",
      projectType: "Choisissez le type de projet qui décrit le mieux votre demande.",
      message: "Décrivez brièvement votre projet.",
    },
    mapLabel: "Carte illustrative de Marrakech",
    mapCaption: "CARTE — MARRAKECH",
    addressLabel: "Adresse",
    address: "Quartier Industriel Sidi Ghanem, Marrakech 40000, Maroc",
    emailLabel: "Email",
    phoneLabel: "Téléphone",
    hoursLabel: "Horaires",
    hours: "Lundi – Vendredi · 8h30 – 18h00",
  },
  en: {
    kicker: "Contact",
    title: "Let’s discuss your project",
    description: "Contact GEOANALYSIS to scope a geology, geophysics or environmental assignment.",
    name: "Name",
    company: "Company",
    email: "Email",
    phone: "Phone",
    optional: "(optional)",
    projectType: "Project type",
    message: "Message",
    projectTypes: [
      { label: "Mineral exploration", value: "mining" },
      { label: "Impact study", value: "impact" },
      { label: "Water resources", value: "water" },
      { label: "Other", value: "other" },
    ],
    send: "Send request",
    success: "Local demo complete. Your request was not sent or saved.",
    demoNote: "Local demo only: your request is not sent or saved.",
    errors: {
      name: "Enter your name.",
      emailRequired: "Enter your email address.",
      emailInvalid: "Enter a valid email address, such as name@company.com.",
      projectType: "Choose the project type that best describes your request.",
      message: "Briefly describe your project.",
    },
    mapLabel: "Illustrative map of Marrakech",
    mapCaption: "MAP — MARRAKECH",
    addressLabel: "Address",
    address: "Industrial District, Sidi Ghanem, Marrakech 40000, Morocco",
    emailLabel: "Email",
    phoneLabel: "Phone",
    hoursLabel: "Hours",
    hours: "Monday – Friday · 8:30 – 18:00",
  },
} satisfies Record<Locale, object>;
