import type { Locale } from "@/lib/i18n";

export const contactPageCopy = {
  fr: {
    kicker: "GEOANALYSIS · MARRAKECH",
    title: "Parlons de votre projet",
    description: "Contactez GEOANALYSIS pour cadrer une mission en géologie, géophysique ou environnement.",
    visualLabel: "Repères · Terrain · Expertise",
    formKicker: "votre demande",
    formTitle: "Décrivez votre projet",
    formDescription: "Quelques lignes suffisent pour nous aider à orienter votre demande.",
    detailsKicker: "À votre écoute",
    detailsTitle: "Restons en contact",
    location: "Marrakech · Maroc",
    name: "Nom",
    company: "Société",
    email: "Email",
    phone: "Téléphone",
    optional: "(facultatif)",
    projectType: "Type de projet",
    message: "Message",
    projectTypes: [
      { label: "Géologie et mines", value: "mining" },
      { label: "Environnement", value: "impact" },
      { label: "Hydrologie et hydrogéologie", value: "water" },
      { label: "Autre", value: "other" },
    ],
    send: "Envoyer la demande",
    sendError: "Votre demande n’a pas pu être envoyée. Réessayez dans quelques instants.",
    rateLimitError: "Trop de demandes ont été envoyées. Réessayez un peu plus tard.",
    success: "Votre demande a bien été envoyée. Nous vous recontacterons bientôt.",
    demoNote: "Vos coordonnées sont transmises de manière sécurisée à GEOANALYSIS.",
    errors: {
      name: "Indiquez votre nom.",
      emailRequired: "Indiquez votre adresse email.",
      emailInvalid: "Saisissez une adresse email valide, par exemple nom@entreprise.ma.",
      projectType: "Choisissez le type de projet qui décrit le mieux votre demande.",
      message: "Décrivez brièvement votre projet.",
    },
    mapLabel: "Carte du Quartier Industriel Sidi Ghanem, Marrakech 40000, Maroc",
    addressLabel: "Adresse",
    address: "Quartier Industriel Sidi Ghanem, Marrakech 40000, Maroc",
    emailLabel: "Email",
    phoneLabel: "Téléphone",
    linkedinLabel: "LinkedIn",
    hoursLabel: "Horaires",
    hours: "Lundi – Vendredi · 8h30 – 18h00",
  },
  en: {
    kicker: "GEOANALYSIS · MARRAKECH",
    title: "Let’s discuss your project",
    description: "Contact GEOANALYSIS to scope a geology, geophysics or environmental assignment.",
    visualLabel: "Context · Fieldwork · Expertise",
    formKicker: "your enquiry",
    formTitle: "Tell us about your project",
    formDescription: "A few lines will help us understand where to start.",
    detailsKicker: "Here to help",
    detailsTitle: "Let’s stay in touch",
    location: "Marrakech · Morocco",
    name: "Name",
    company: "Company",
    email: "Email",
    phone: "Phone",
    optional: "(optional)",
    projectType: "Project type",
    message: "Message",
    projectTypes: [
      { label: "Geology and mining", value: "mining" },
      { label: "Environment", value: "impact" },
      { label: "Hydrology and hydrogeology", value: "water" },
      { label: "Other", value: "other" },
    ],
    send: "Send request",
    sendError: "Your request could not be sent. Please try again shortly.",
    rateLimitError: "Too many requests were sent. Please try again later.",
    success: "Your request has been sent. We will be in touch soon.",
    demoNote: "Your details are sent securely to GEOANALYSIS.",
    errors: {
      name: "Enter your name.",
      emailRequired: "Enter your email address.",
      emailInvalid: "Enter a valid email address, such as name@company.com.",
      projectType: "Choose the project type that best describes your request.",
      message: "Briefly describe your project.",
    },
    mapLabel: "Map of Sidi Ghanem Industrial District, Marrakech 40000, Morocco",
    addressLabel: "Address",
    address: "Industrial District, Sidi Ghanem, Marrakech 40000, Morocco",
    emailLabel: "Email",
    phoneLabel: "Phone",
    linkedinLabel: "LinkedIn",
    hoursLabel: "Hours",
    hours: "Monday – Friday · 8:30 – 18:00",
  },
} satisfies Record<Locale, object>;
