import type { Locale } from "@/lib/i18n";

export const projectPageCopy = {
  fr: {
    indexTitle: "Réalisations",
    indexLead: "Sélection de missions conduites pour des opérateurs miniers, institutions et collectivités.",
    filterLabel: "Filtrer les réalisations par domaine",
    allDomains: "Tous les domaines",
    activeFilter: "Filtre actif",
    projectCount: "réalisations",
    detailBack: "Toutes les réalisations",
    galleryKicker: "Galerie",
    galleryTitle: "Visuels de la mission",
    galleryImage: "Galerie",
    descriptionKicker: "La mission",
    descriptionTitle: "Description du projet",
    methodologyKicker: "Méthodologie",
    methodologyTitle: "Étapes de la mission",
    resultsKicker: "Résultats",
    resultsTitle: "Résultats clés",
    contactTitle: "Un projet similaire ?",
    contactLead: "Décrivez votre contexte. Notre équipe vous répond avec une proposition méthodologique.",
    contactAction: "Parler de votre projet",
  },
  en: {
    indexTitle: "Projects",
    indexLead: "A selection of assignments for mining operators, institutions and local authorities.",
    filterLabel: "Filter projects by field",
    allDomains: "All domains",
    activeFilter: "Active filter",
    projectCount: "projects",
    detailBack: "All projects",
    galleryKicker: "Gallery",
    galleryTitle: "Project visuals",
    galleryImage: "Gallery",
    descriptionKicker: "The assignment",
    descriptionTitle: "Project description",
    methodologyKicker: "Methodology",
    methodologyTitle: "Assignment steps",
    resultsKicker: "Results",
    resultsTitle: "Key results",
    contactTitle: "Planning a similar project?",
    contactLead: "Describe your context. Our team will respond with a methodological proposal.",
    contactAction: "Discuss your project",
  },
} satisfies Record<Locale, Record<string, string>>;
